AWSTemplateFormatVersion: "2010-09-09"
Description: "Creates S3 bucket"

Resources:
    S3Bucket: # logical id/name
        Type: AWS::S3::Bucket # type of resource
        Properties:
            BucketName: abcd123sdp
Outputs:
    BucketName:
        Value: !Ref 'S3Bucket'
